name: baby_monitor_app
description: "Baby Monitor with Laravel API"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.4.0" # Tambahkan constraint ini
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # HTTP & WebSocket
  http: ^1.2.0
  web_socket_channel: ^2.4.0

  # Audio & Notifications
  audioplayers: ^6.4.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.1

  # UI & Navigation
  go_router: ^14.2.8
  gap: ^3.0.1

  # Utilities
  shared_preferences: ^2.3.0
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
